<?php

/* Generated by Eregansu Install at 2013-02-27 16:55:25 */

define('INSTANCE_ROOT', realpath(dirname(__FILE__) . '/..') . '/');
define('PUBLIC_ROOT', realpath(dirname(__FILE__)) . '/');

require(INSTANCE_ROOT . 'eregansu/framework/platform.php');

$app->process($request);
