<?php

/* Application configuration for lodscope - generated by Eregansu Install at 2013-02-27 21:01:50*/

define('APP_NAME', 'lodscope');

/* Application configuration for the 'setup' module */
$CLI_ROUTES['setup'] = array('file' => PLATFORM_ROOT . 'setup/cli.php', 'class' => 'CliSetup', 'fromRoot' => true);

/* Application configuration for the 'login' module */

/* Application configuration for the 'silk' module */
$CLI_ROUTES['silk'] = array('file' => PLATFORM_ROOT . 'silk/app.php', 'class' => 'Silk', 'fromRoot' => true);

/* Application configuration for the 'views' module */
$CLI_ROUTES['update-views'] = array('file' => '/Users/mo/2012/eregansu/views/update.php', 'class' => 'ViewsUpdate', 'description' => 'Rebuild templates within the current directory');
$TEMPLATE_ENGINES['twig'] = array('file' => '/Users/mo/2012/eregansu/views/twig.php', 'ext' => 'twig', 'class' => 'TwigViewsEngine');

/* Application configuration for the 'lodscope' module */
define('HTTP_MODULE_NAME', 'lodscope');
define('HTTP_MODULE_CLASS_PATH', 'app.php');
define('HTTP_MODULE_CLASS', 'lodscopeApp');

