<?php

/* Instance configuration for sobek - generated by Eregansu Install at 2013-02-27 16:55:25*/

/* Each copy of an application must have a unique INSTANCE_NAME
 * If you use (either directly or directly) the "cluster" module,
 * then INSTANCE_NAME is used to determine which cluster this
 * is part of.
 */
define('INSTANCE_NAME', 'sobek');

/* The "heartbeat" module will use HOST_NAME in preference to INSTANCE_NAME if
 * defined.
 */
/* define('HOST_NAME', 'sobek'); */

/* With the below defined, if jQuery is used by any pages, it will be loaded
 * from Google's servers. If you comment it out or remove it, Eregansu will
 * expect to load jQuery from SCRIPTS_IRI/jquery/jquery-<version>/jquery.min.js
 */
define('SCRIPTS_USE_GAPI', true);

/* Uncomment the below to override the path used to serve scripts,
 * which by default is set to the root URL of your application.
 */
/* define('SCRIPTS_IRI', 'http://static1.example.com/scripts/'); */

/* For applications which make use of the object store, set
 * OBJECT_CACHE_ROOT to the absolute path of a directory where
 * a JSON-encoded copy of each stored object should be written to.
 * Objects are stored at <OBJECT_CACHE_ROOT>/<kind>/<uuid[0..2]>/<uuid>.json
 * If specified, OBJECT_CACHE_ROOT must include a trailing slash.
 */
/* define('OBJECT_CACHE_ROOT', '/shared/cache/objects/'); */

define('EREGANSU_DEBUG', true);

if(isset($_SERVER['http_proxy'])) putenv('http_proxy=' . $_SERVER['http_proxy']);
if(isset($_SERVER['https_proxy'])) putenv('https_proxy=' . $_SERVER['https_proxy']);
if(isset($_SERVER['no_proxy'])) putenv('no_proxy=' . $_SERVER['no_proxy']);

define('LODSCOPE_FETCH_VOCABULARIES', true);
define('CURL_ALWAYS_VERBOSE', true);
define('CURL_CACHE_DIR', INSTANCE_ROOT . 'cache/curl/');