<?php
$examples = array(
	'http://yawdle.com/' => 'Yawdle',
	'http://dbpedialite.org/things/20501277#id' => 'Florence and the Machine on dbpedialite',
	'http://www.bbc.co.uk/nature/life/Common_Toad#species' => 'The Common Toad on BBC Wildlife Finder',
	'http://www.bbc.co.uk/programmes/p00wpvpn#programme' => 'Treasures of Ancient Rome on BBC Programmes',
	'http://sws.geonames.org/146669/' => 'Cyprus on Geonames',
	'http://creativecommons.org/licenses/by/3.0/' => 'Creative Commons 3.0 Unported license',
	'http://purl.org/dc/terms/hasVersion' => 'dct:hasVersion from the DCMI Metadata Terms',
	'http://rdf.freebase.com/ns/en.bbc' => 'BBC on Freebase',
	'http://data.nature.com/ns/articles/10.1038/445239a' => 'Behind the hunt for the Higgs boson on Nature.com',
	'http://viaf.org/viaf/120719476/' => 'Ruth Rendell on VIAF',
	'http://data.open.ac.uk/bbc/b00mfl7n' => 'OU on the BBC: Frozen Planet from the Open University',
	'http://musicbrainz.org/artist/ba2f4f3b-0293-4bc8-bb94-2f73b5207343#_' => 'Underworld on MusicBrainz',
	'http://data.ordnancesurvey.co.uk/id/country/scotland' => 'Scotland on Ordnance Survey',
	'http://worldbank.270a.info/void.ttl#world-bank' => 'World Bank Linked Data',
	'http://www.run4it.com/a7abd2e7-f8c7-fa04-4502-683de1096fa3#product' => 'Nathan Triangle WaistPack on Run4It.com',
	'http://moustaki.org/foaf.rdf#moustaki' => 'Yves Raimond’s profile',
	'http://thespace.org/items/s0000cgu#series' => 'Band on the Wall on The Space',
	'http://www.alpinebikes.com/ecf6db90-cb40-0f24-79cf-5f94473a408e#product' => 'Bianchi Infinito Athena on Alpine Bikes',
	'http://neva.li/#me' => 'Mo McRoberts’s profile',
	'http://data.nytimes.com/51535120590522012773' => 'George Owell on the New York Times',
	'http://www.legislation.gov.uk/ukpga/1988/48/section/35' => 'Section 35 of the Copyright, Designs and Patents Act 1988 on legislation.gov.uk',
	'http://reference.data.gov.uk/id/open-government-licence' => 'The Open Government Licence',
	'http://sameas.org/rdf?uri=http%3A%2F%2Fdbpedialite.org%2Fthings%2F21177839%23id' => 'sameas.org lookup for the entry for “Fire” on dbpedialite',
);
