<?php

/*
 * Copyright 2013 Mo McRoberts.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

$examples = array(
	'http://dbpedialite.org/things/20501277#id' => 'Florence and the Machine on dbpedialite',
	'http://www.bbc.co.uk/nature/life/Common_Toad#species' => 'The Common Toad on BBC Wildlife Finder',
	'http://www.bbc.co.uk/programmes/p00wpvpn#programme' => 'Treasures of Ancient Rome on BBC Programmes',
	'http://sws.geonames.org/146669/' => 'Cyprus on Geonames',
	'http://creativecommons.org/licenses/by/3.0/' => 'Creative Commons 3.0 Unported license',
	'http://purl.org/dc/terms/hasVersion' => 'dct:hasVersion from the DCMI Metadata Terms',
	'http://rdf.freebase.com/ns/en.bbc' => 'BBC on Freebase',
);

$form = array();
$form[] = '<form method="get" action="' . _e($app_root) . '">';
$form[] = '<input type="text" name="uri" value="' . _e($uri) . '" size="64">';
$form[] = '<input type="submit" name="go" value="Go">';
$form[] = '</form>';

$footer = array(
	'</article>',
	'<footer>',
	'<p>Copyright &copy; 2013 <a href="http://neva.li/">Mo McRoberts</a>.<br>LODscope is <a href="https://github.com/nevali/lodscope">open source software</a> released under the terms of the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>.</p>',
	'</footer>',
);

if(isset($object))
{
	$type = 'text/html';
	if(isset($object[$uri]))
	{
		$inst = $object[$uri];
		$object->htmlTitle = $inst->title();
		$jumpLink = '<p><a class="local" href="#' . _e($inst->htmlLinkId()) . '">Jump to ' . _e($uri) . '</a></p>';
	}
	else
	{
		$jumpLink = '';
	}
	$query = '?uri=' . urlencode($uri);
	$header = array(
		'<header>',
		'<h1>' . _e($object->htmlTitle) . '</h1>',
		'<p>Also available as:</p>',
		'<ul class="resource-types">',
		'<li><a href="'. _e($app_root . 'index.ttl' . $query) . '">Turtle</a></li>',
		'<li><a href="'. _e($app_root . 'index.n3' . $query) . '">N3</a></li>',
		'<li><a href="'. _e($app_root . 'index.nt' . $query) . '">N-Triples</a> (<a href="' . _e($app_root . 'index.text' . $query) . '">Text</a>)</li>',
		'<li><a href="'. _e($app_root . 'index.rdf' . $query) . '">RDF/XML</a></li>',
		'<li><a href="'. _e($app_root . 'index.json' . $query) . '">JSON</a> (<a href="' . _e($app_root . 'index.jsonld' . $query) . '">JSON-LD</a>)</li>',
		'</ul>',
		implode("\n", $form),
		'</header>',
		'<article>',	
		$jumpLink,
	);
	$object->htmlPreBody = implode("\n", $header);
	$object->htmlPostBody = implode("\n", $footer);
	$object->htmlLinks[] = array('rel' => 'stylesheet', 'href' => $skin_iri . 'global.css', 'type' => 'text/css');
	$buf = $object->serialise($type, false, $request, false);
}
else
{
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>LODscope</title>
		<link rel="stylesheet" type="text/css" href="<?php e($skin_iri . 'global.css'); ?>">
	</head>
	<body>
		<header>
			<h1>LODscope</h1>
		</header>
		<article>
			<p>
				LODscope is a simple linked data browser. Type or paste a
				linked data URI into the field below and press <i>Go</i> to fetch and browse the data at that URI.
			</p>
			<?php	

echo implode("\n", $form);
?>
<h2>Examples</h2>
<?php

	echo '<ul>';
	foreach($examples as $uri => $title)
	{
		echo '<li><a href="' . _e($app_root . '?uri=' . urlencode($uri)) . '">' . $title . '</a></li>';
	}
	echo '</ul>';

	echo '</article>';
	echo implode("\n", $footer);
	echo '</body>';
	echo '</html>';
}
