<?php

/*
 * Copyright 2013 Mo McRoberts.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

require_once(dirname(__FILE__) . '/examples.php');

$form = array();
$form[] = '<form method="get" action="' . _e($app_root) . '">';
$form[] = '<label for="uri">Universal identifier:</label>';
$form[] = '<input type="text" id="uri" name="uri" value="' . _e($uri) . '" size="64">';
$form[] = '<input type="submit" name="go" value="Go">';
$form[] = '</form>';

$footer = array(
	'</article>',
	'<footer>',
	'<p>Copyright &copy; 2013 <a href="http://neva.li/">Mo McRoberts</a>.<br>LODscope is <a href="https://github.com/nevali/lodscope">open source software</a> released under the terms of the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>.</p>',
	'</footer>',
);

if(isset($object))
{
	$type = 'text/html';
	if(isset($object[$uri]))
	{
		$inst = $object[$uri];
		$object->htmlTitle = $inst->title();
		$jumpLink = '<p><a class="local" href="#' . _e($inst->htmlLinkId()) . '">Jump to ' . _e($uri) . '</a></p>';
	}
	else
	{
		$jumpLink = '';
	}
	if(!strlen($object->htmlTitle))
	{
		$object->htmlTitle = $uri;
	}
	$query = '?uri=' . urlencode($uri);
	$header = array(
		'<header>',
		'<h1>' . _e($object->htmlTitle) . '</h1>',
		'<p><a class="visit" href="' . _e($uri) . '">Visit page for this item</a>.</p>',
		'<p>This data is also available as:</p>',
		'<ul class="resource-types">',
		);
	foreach($serialisations as $path => $info)
	{
		$item = '<li><a href="' . _e($path) . '">' . $info['title'] . '</a>';
		foreach($info['alt'] as $altpath => $altinfo)
		{
			$item .= ' (<a href="' . _e($altpath) . '">' . $altinfo['title'] . '</a>)';
		}
		$item .= '</li>';
		$header[] = $item;
	}
	$header[] = '</ul>';
	$header[] = implode("\n", $form);
	$header[] = '</header>';
	$header[] = '<article>';
	$header[] = $jumpLink;
	$object->htmlPreBody = implode("\n", $header);
	$object->htmlPostBody = implode("\n", $footer);
	$object->htmlLinks = $links;
	$object->htmlLinks[] = array('rel' => 'stylesheet', 'href' => $skin_iri . 'global.css', 'type' => 'text/css');
	$buf = $object->serialise($type, false, $request, false);
}
else
{
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>LODscope</title>
		<link rel="stylesheet" type="text/css" href="<?php e($skin_iri . 'global.css'); ?>">
		<?php $this->links(); ?>
	</head>
	<body>
		<header>
			<h1>LODscope</h1>
		</header>
		<article>
			<p>
				LODscope is a simple linked data browser. Type or paste a
				linked data URI into the field below and press <i>Go</i> to fetch and browse the data at that URI.
			</p>
			<?php	
if(isset($uri) && strlen($uri))
{
		echo '<p class="error">Unfortunately, LODscope wasn’t able to retrieve any data for the identifier that you specified. <a href="'. _e($uri) . '">Visit the page instead</a>?</p>';
}
echo implode("\n", $form);
?>
			<p>
				You	can also use the following bookmarklet to browse data with
				LODscope. Drag it into your browser’s toolbar to install.
				When you’re viewing a page you can press the button to
				browse the data.
			</p>
			<p><a class="bookmarklet" href="javascript:location.href=&#039;http://lodscope.parthenon.org.uk/?uri=&#039;+encodeURIComponent(location.href);">LODscope</a></p>

<h2>Examples</h2>
<?php

	echo '<ul>';
	foreach($examples as $uri => $title)
	{
		echo '<li><a href="' . _e($app_root . '?uri=' . urlencode($uri)) . '">' . $title . '</a></li>';
	}
	echo '</ul>';

	echo '</article>';
	echo implode("\n", $footer);
	echo '</body>';
	echo '</html>';
}
